name: Build PDF
on:
  push:
  workflow_dispatch:
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - uses: actions/checkout@v2
      - run: apk add chromium
      - run: npm i mdpdf -g
      - run: mkdir ./out
      - run: cat files.txt | sed -z -e 's/\r//g' | xargs -I {file} mdpdf {file} -o out/{file}.md
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: out/
