name: Build PDF
on: [push]
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo sh ./assets/install-pandoc.sh
      - run: sudo sh ./assets/install-wkhtmltopdf.sh
      - run: sudo sh ./assets/build.sh
      - uses: actions/upload-artifact@master
        with:
          name: exported document
          path: out/output.pdf
