name: Build PDF
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y pandoc wkhtmltopdf
      - run: ./assets/build.sh
      - uses: actions/upload-artifact@master
        with:
          name: curriculum-vitae
          path: out/output.pdf
