name: Build PDF
on:
  push:
  workflow_dispatch:
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: npm install -g md-to-pdf
      - run: mkdir ./out
      - run: md-to-pdf ZOI/VR_Tracker/VR_Tracker.md --output out/output.pdf --md-file-encoding utf-8
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: out/
