name: Build PDF
on:
  push:
  workflow_dispatch:
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: npm install -g markdown-pdf --ignore-scripts
      - run: mkdir ./out
      - run: markdown-pdf ZOI/VR_Tracker/VR_Tracker.md -o out/output.pdf
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: out/
