name: Build PDF
on:
  push:
  workflow_dispatch:
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install chromium node
      - run: npm i md-to-pdf -g
      - run: mkdir ./out
      - run: cat files.txt | md-to-pdf > out/output.pdf
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: out/
