name: Build PDF
on:
  push:
  workflow_dispatch:
jobs:
  Build-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y nodejs fonts-ipafont
      - run: npm install -g md-to-pdf
      - run: ./assets/build-pdf.sh
      - uses: actions/upload-artifact@master
        with:
          name: pdf
          path: out/
